# Generated by Django 4.2.2 on 2023-11-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default=True, max_length=50, null=True),
        ),
    ]
