# Generated by Django 4.2.2 on 2023-11-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bids_comments_auctionlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlist',
            old_name='product_price',
            new_name='startin_bid',
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='product_description',
            field=models.TextField(default=True, null=True),
        ),
    ]
