# Generated by Django 4.2.2 on 2023-11-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_product_price_auctionlist_startin_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='product_description',
            field=models.CharField(default=True, max_length=100, null=True),
        ),
    ]
