# Generated by Django 4.2.2 on 2023-11-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auctionlist_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='product_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
