# Generated by Django 4.2.2 on 2023-11-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auctionlist_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
