# Generated by Django 4.2.2 on 2023-11-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auctionlist_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
