# Generated by Django 4.2.2 on 2023-11-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auctionlist_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
