# Generated by Django 4.2.2 on 2023-11-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_watchlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='name',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='name',
            field=models.ManyToManyField(blank=True, null=True, to='auctions.auctionlist'),
        ),
    ]
