# Generated by Django 4.2.2 on 2023-11-22 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_remove_watchlist_name_watchlist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='name',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionlist'),
        ),
    ]
